### ISSUE TITLE
Running the Python command 'Asm4_newLCS' failed:

### ISSUE THREAD

**Issue by Ahorvath94** [Zolko-123/FreeCAD_Assembly4#101]
Hi all,

I recently installed the FreeCAD Assembly4 workbench and I get an error saying that I cannot create a local coordinate system when I try to create one for a part. However, FreeCAD actually does add the coordinate system, and I can edit the datum etc. as necessary. I am not sure if Assembly4 is supposed to be able to function with FreeCAD 0.18 but that is what I am using and I found it in the add-on manager. This is not hindering me from getting anything done but there is an error shown in FreeCAD nonetheless and figured I'd write it up. I will continue looking into it! Thanks!

Here is my setup:

OS: Windows 10
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.4 (GitTag)
Build type: Release
Branch: releases/FreeCAD-0-18
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 3.6.6
Qt version: 5.6.2
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)

Error:

Running the Python command 'Asm4_newLCS' failed:
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\FreeCAD\Mod\Assembly4\newDatumCmd.py", line 147, in Activated
    Gui.Selection.addSelection( App.ActiveDocument.Name, parentContainer.Name, createdDatum.Name+'.' )

type must be 'DocumentObject[,subname[,x,y,z]]' or 'DocumentObject, list or tuple of subnames'

**Comment by Zolko-123** [comment]
Assembly4 is not compatible with FreeCAD v0.18, it needs the new App::Link interface introduced in v0.19. Some functions might work, but it's sheer luck.
