### ISSUE TITLE
Usability: After a local coordinate system is created, we should enter "Edit Datum" directly

### ISSUE THREAD

**Issue by cheuksan** [Zolko-123/FreeCAD_Assembly4#103]
Once I created a new local coordinate system, I always enter the "edit datum" dialog manually. It is also true with most of the assembly 4 tutorial videos on youtube. Can we go directly into "Edit Datum" without clicking after a new LCS is created?

https://www.youtube.com/channel/UCpdgfEnmKNi8iv_A66efg9Q/videos

![Screenshot from 2020-08-29 10-32-12](https://user-images.githubusercontent.com/64454019/91642787-07724a00-e9e3-11ea-8139-9527acdff2a9.png)

![Screenshot from 2020-08-29 10-32-40](https://user-images.githubusercontent.com/64454019/91642786-06d9b380-e9e3-11ea-8f35-47025024cc67.png)

**Comment by Zolko-123** [comment]
I'll have to look

**Comment by Zolko-123** [comment]
Done, will be in the next release

**Comment by wang02139** [comment]
thanks
