### ISSUE TITLE
In "Place linked Part", Rot X/Y/Z needs a UI

### ISSUE THREAD

**Issue by wang02139** [Zolko-123/FreeCAD_Assembly4#104]
When I use "Place linked Part", I often need to use Rot X / Y / Z repeatedly to find the correct placement. It's hard to know which one is the right rotation, or which direction it'll rotate. It takes many tries to find the correct axis and number of rotations. It'd be nice to have UI for it in the main window, similar to the "Transform" UI for parts. This problem is also shown repeatedly in the assembly 4 tutorials:

https://www.youtube.com/channel/UCpdgfEnmKNi8iv_A66efg9Q/videos

![Screenshot from 2020-08-29 15-05-40](https://user-images.githubusercontent.com/8675499/91646913-58953480-ea09-11ea-9194-527389eceb7f.png)

**Comment by Zolko-123** [comment]
If you have proposals to make, I'll happily integrate them into the code. Thank-you
