### ISSUE TITLE
super() argument 1 must be type, not classobj

### ISSUE THREAD

**Issue by Qik000** [Zolko-123/FreeCAD_Assembly4#120]
When i installed this plugin i couldnt use it at all, the error from the title was displayed and no toolbars were loaded. I am using Linux

**Comment by Zolko-123** [comment]
What colour is your Linux ?

**Comment by Qik000** [comment]
> What colour is your Linux ?

this happens on my machines running Ubuntu, Kubuntu and Debian

**Comment by Zolko-123** [comment]
Are you using FreeCAD 0.18 ?

**Comment by Qik000** [comment]
> Are you using FreeCAD 0.18 ?

Yes, 18.4
