### ISSUE TITLE
Bring LCS of part into assembly

### ISSUE THREAD

**Issue by xoviat** [Zolko-123/FreeCAD_Assembly4#121]
I I have the following setup:

```
Assembly1
     Assembly2
           Part1
               LCS1
      Assembly3
            Part2
                LCS2
```

I haven't found how to join Assembly2 and Assembly3 with LCS1 and LCS2. I can't create a new LCS in the assembly based on the part LCS. Thoughts?

**Comment by Zolko-123** [comment]
The command `Import Datum` serves exactly this purpose: it allows to import (create a clone of) LCS1 into Assembly2, and LCS2 into Assembly3.
