### ISSUE TITLE
Strange behavior when moving LCS from Model(assembly) into Part

### ISSUE THREAD

**Issue by AcumenDev** [Zolko-123/FreeCAD_Assembly4#128]
When I move LCS from Model(assembly) into Part this operation destroys the object Boby

1)Example create one part and assembly model 
![Screenshot from 2020-10-03 18-55-22](https://user-images.githubusercontent.com/675860/94995945-47ac8580-05aa-11eb-944f-edda88869f91.png)
2)I created LCS in the wrong place 
![Screenshot from 2020-10-03 18-55-54](https://user-images.githubusercontent.com/675860/94996002-a4a83b80-05aa-11eb-943d-863853e88653.png)
3)now I'm moving an LCS to Part. This operation broke the Body(steps fo create body now in body level)
![Screenshot from 2020-10-03 18-56-09](https://user-images.githubusercontent.com/675860/94996044-e2a55f80-05aa-11eb-945f-4d0e3de277c6.png)
![Screenshot from 2020-10-03 18-56-17](https://user-images.githubusercontent.com/675860/94996045-e3d68c80-05aa-11eb-959e-81df49b52819.png)

Thank you for Assembly 4

FreeCAD Assembly 4 workbench
Current version 0.9.9, 2020-09-24

OS: Debian GNU/Linux 10 (buster) (GNOME/gnome)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.22522 (Git) AppImage
Build type: Release
Branch: master
Hash: d8e476ef428017900dfe0f9359ba448503c216f9
Python version: 3.8.5
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by Zolko-123** [comment]
> _I created LCS in the wrong place_

yes, this happens with me also sometimes, but then I delete the LCS and create it in the correct place.

**Comment by AcumenDev** [comment]
> > _I created LCS in the wrong place_
> 
> yes, this happens with me also sometimes, but then I delete the LCS and create it in the correct place.

This behavior Freecad itself or assembly 4?
There is another question: where the correct place do create LCS in the part or in the body?
May be correct to create LCS in an active node(part for example) in the project tree, not in a dedicated node (Because of these behaviors LCS are often created in the wrong place namely in the Assembly model node.)?
