### ISSUE TITLE
International symbols not shown correctly in Body names created within A4 workbench

### ISSUE THREAD

**Issue by timtashpulatov** [Zolko-123/FreeCAD_Assembly4#130]
If a new Body is created in Assembly 4 workbench, and the new Body's name contains international characters (Cyrillic for example), these symbols are shown as underscores.

![image](https://user-images.githubusercontent.com/5108024/95047581-0376cd80-06ef-11eb-82fc-e261ec7218fb.png)

When a Body is created using Part Design workbench, international symbols are shown correctly.

**Comment by Zolko-123** [comment]
> _When a Body is created using Part Design workbench, international symbols are shown  correctly_.

When a Body is created using PartDesign workbench, it is called "Body" therefore its name doesn't contain any "international" characters. You're confusing "Name" and "Label"

**Comment by timtashpulatov** [comment]
> When a Body is created using PartDesign workbench, it is called "Body" therefore its name doesn't contain any "international" characters. You're confusing "Name" and "Label"

Most likely I am confusing Name and Label, indeed. Still could something be done to avoid those underscores when using international characters? Thanks.

**Comment by Zolko-123** [comment]
did you try to rename the Body that you created ?

**Comment by timtashpulatov** [comment]
Renaming the Body seems to work. Underscores are still shown in Part List when inserting link to a part, but I guess I can live with it.

1. Body created with int'l name:
![image](https://user-images.githubusercontent.com/5108024/95109468-4c597100-0745-11eb-8d44-0fe90a714069.png)

2. Body renamed:
![image](https://user-images.githubusercontent.com/5108024/95109613-7e6ad300-0745-11eb-9026-e1f0466dbac4.png)
