### ISSUE TITLE
Edit part workflow

### ISSUE THREAD

**Issue by xoviat** [Zolko-123/FreeCAD_Assembly4#133]
Similar to other CAD software, Assembly4 should have the 'edit part' workflow. When in an assembly, the user should be able to right click on a part, and the workbench should temporarily switch to the 'part design' workbench for the part. when done, the user should be able to right click on the part and click 'Done', whereupon the workbench will switch back to assembly4.

**Comment by Zolko-123** [comment]
This is a frequent confusion: the _PartDesign_ workbench doesn't design **Parts**, it designs **Bodies**. 

If you right-click on a Body and select **Toggle active body** it will switch to the _PartDesign_ workbench.
