### ISSUE TITLE
Measurement changes were not merged to master

### ISSUE THREAD

**Issue by xoviat** [Zolko-123/FreeCAD_Assembly4#135]
See https://github.com/Zolko-123/FreeCAD_Assembly4/compare/development...master 

The problem is that git thinks master is ahead of development because of #131

**Comment by Zolko-123** [comment]
Ah. And is this feature in the development branch ? (I never use non-SI units)

**Comment by xoviat** [comment]
The feature is in the development branch. These commands should fix it:

(on master)
```
git checkout fb7862706f98fd0bf2e54ba6c1aa4d04336e6571 -- .
git commit -a -m "reset master to development"
git push
```

fb7862706f98fd0bf2e54ba6c1aa4d04336e6571 is the latest commit on development.

**Comment by Zolko-123** [comment]
Should be fixed, can you please check ?
