### ISSUE TITLE
Not able to set additional coordinate system on assembly

### ISSUE THREAD

**Issue by kravietz81** [Zolko-123/FreeCAD_Assembly4#144]
Hello.

I stuck on setting additional coordinate system on simple assembly. Can you guide me how to deal with this issue?? I've tried different settings without success.

![image](https://user-images.githubusercontent.com/63076001/99781236-e0c23c00-2b17-11eb-8b94-c41024bfe5cc.png)

And what does this symbol near coordinate system name means??

![image](https://user-images.githubusercontent.com/63076001/99790989-38b36f80-2b25-11eb-8e65-9c4e85b17aee.png)

Do you need files?? Or you can help without seeing them??

**Comment by Zolko-123** [comment]
please use the forum for help

**Comment by kravietz81** [comment]
OK.

So what we should comment here??
