### ISSUE TITLE
Animation dialog does not correctly store previous state

### ISSUE THREAD

**Issue by donovaly** [Zolko-123/FreeCAD_Assembly4#161]
I don't know if this is a bug or missing feature, however, it would be very helpful if the animation dialog would state the previous state since at the moment you have to reset the value range on every call of the dialog.

Here is an example:
![koT4Pwzt8i](https://user-images.githubusercontent.com/1828501/104229464-9e98e500-544c-11eb-91e6-e90d2371c1f5.gif)

So you can see the float ran from 0 to 360 but after the reopening there is no range anymore. It stored the last value and put this to both range fields.
However, the state of the Loop option is correctly stored.

**Comment by Zolko-123** [comment]
This has been asked before, I have to think how to implement it (a global variable may-be)

**Comment by donovaly** [comment]
> This has been asked before, I have to think how to implement it (a global variable may-be)

Maybe you can use the way you store the current angle. In my example above you see then on reopening the animation dialog the angle 74. This was obviously the last angle position and it is still available after closing the dialog. So maybe you can save the range values the same way.

**Comment by Zolko-123** [comment]
that value is the **current** variable value

**Comment by donovaly** [comment]
> that value is the **current** variable value

Ah, OK. However, you already store the state of the Loop and Pendulum property, so it should be possible to store the values of the range the same way, no?

**Comment by Alonso-JAMM** [comment]
Maybe a dictionary could be used to store the value, range, step, and other data of a variable. For example, the Variables object could have a property "App::PropertyPythonObject" that would store a dictionary containing the animation data related to all variables. So the dictionary would look like this:
`{"angle1": {"value": 74, "Range_Begin": 0, "Range_End": 360, "step":1}, 
   "angle2":{"value": 10, "Range_Begin": 5, "Range_End": 20, "step":1}}`

Then the data stored in the dictionary could be used by the animation window. This would be helpful in storing the animation data of multiple variables at the same time

**Comment by Zolko-123** [comment]
This should be fixed in the recent merge of Thowil's PR
