### ISSUE TITLE
variable description not visible or changeable

### ISSUE THREAD

**Issue by donovaly** [Zolko-123/FreeCAD_Assembly4#162]
When creating a variable one can set a description. This is very useful when you have many variables. However, after the creation one cannot see the description. (maybe I have overseen something?)

It would be helpful that the description appears in the properties and maybe also as tooltip for the variable combobox in the animation dialog.

**Comment by Zolko-123** [comment]
The description should be visible in the tooltip if you leave the mouse hover over the variable name.

As for adding a description later, it's a good idea, I have to check how to do it

**Comment by donovaly** [comment]
> The description should be visible in the tooltip if you leave the mouse hover over the variable name.

This doesn't work for me:

![bQ117VfDUm](https://user-images.githubusercontent.com/1828501/104316068-372a7600-54dc-11eb-89ce-cf94d756423f.gif)

I can also not see the description anywhere else. Maybe you could add a property holding the description?

**Comment by Zolko-123** [comment]
did you try if you select "Variables" in the tree and hoover over the name in the property panel ?

**Comment by donovaly** [comment]
> did you try if you select "Variables" in the tree and hoover over the name in the property panel ?

Not yet. But this works, thanks -> we need a proper documentation ;-)
As I wrote, I volunteer, but cannot yet estimate when I will find the time.
