### ISSUE TITLE
symetrical part

### ISSUE THREAD

**Issue by Zolko-123** [Zolko-123/FreeCAD_Assembly4#166]
To create a symmetrical part of an inserted part (link):

- Create a new App::Part, ask user about it's name and symmetry plane (XY, XZ, YZ)
- place that part into the Parts folder
- Create a Draft_Clone of the chosen App::Link (inserted part)
- Move that clone into the App::Part
- Create a Part::Mirroring (need to ask about which plane to make symmetry. Probably in the first dialog)
- Move that mirror to the App::Part
- hide the clone
- Launch Asm4 "Insert Part" with that symmetrical part

**Comment by rolfbachmann** [comment]
Hi, I need a simple mirrored body in my project and I found this issue which really helps me.

What I don't understand is the clone?

1. I've a body (BodyLeft)
2. In in the "Part" workbench I create a mirror which gives me a "BodyLeft (Mirror #1)"
3. Then I create a new Part (BodyRight), put it in App::Part
4. I put the "BodyLeft (Mirror #1)" into the Part (BodyRight)
5. Now I can launch Asm4 and do "Insert Part"

Are there any issues/side effects when I do it like this, without the clone?

**Comment by Zolko-123** [comment]
Hi, good catch, I don't know. May-be the intermediate step of creating a clone is unnecessary. It would be nice if you could report after your test.

**Comment by rolfbachmann** [comment]
Hi, again. Nop. I did a short test and it didn't work. The clone is needed. Otherwise the base part of the mirror (BodyLeft in my case) is not available on the "Insert Part" dialog anymore.

**Comment by Zolko-123** [comment]
OK, thanks for reporting

**Comment by Zolko-123** [comment]
This is now done in v0.9.15. A Link is used instead of a Draft.clone.
