### ISSUE TITLE
Add translations to A4

### ISSUE THREAD

**Issue by luzpaz** [Zolko-123/FreeCAD_Assembly4#173]
https://wiki.freecadweb.org/Translating_an_external_workbench
https://github.com/kbwbe/A2plus/pull/416

**Comment by Zolko-123** [comment]
Done in the development branch (future v0.10)

**Comment by Zolko-123** [comment]
done in latest v0.10, please test and report  (though I don't know how to add/update this)

**Comment by luzpaz** [comment]
@yorikvanhavre lets add it to crowdin ? + what's the external workbench author workflow to push/pull translations?

**Comment by yorikvanhavre** [comment]
Sure! If you want, @Zolko-123 I need your crowdin username, and I'll add you as admin to https://crowdin.com/project/freecad-addons then you can upload your ts file there
