### ISSUE TITLE
Nothing appened when clicking "create new coordinate system in part" while a sketch is selected.

### ISSUE THREAD

**Issue by rponthieu** [Zolko-123/FreeCAD_Assembly4#182]
When I select the master sketch of my assembly and click "create new coordinate system in part" nothing append.

I went a bit in the code and try to add print to console to see what is ran and adding it just after `def Activated(self)` (in newDatum class) does not print to the report view as it should (which mean Activated function is not even run i guess?).

It is a minor disagrement as I just have to select nothing or the Model to get the new coordinate system creation running. 

However it is a bit of a pain when I create many LCS because my workflow is : select Model => click create new coordinate system => place it => click ok. And then the master sketch is selected (so i have to unselect it each time, a bit of a pain when creating many LCS).

I hope it makes sense and it is not because I have a weird way of using ASM4. 

Thanks for the work, I hope I'll be able to contribute soon.

Best,
R

**Comment by Zolko-123** [comment]
Good point: this is fixed in the development branch now, will be released to master with a new version
