### ISSUE TITLE
"<Exception> type must be bool, not str" while restoring configuration

### ISSUE THREAD

**Issue by pankuleczka** [Zolko-123/FreeCAD_Assembly4#192]
attached are 3 files (inside zip):
`test1.FCStd` - with 2 parts done in Part Design with LCS added later in Assembly 4, `test1asm.FCStd` - with assembly, which later became sub-assembly used in `test1asm2.FCStd`

for some reason I'm not able to use configurations in both assemblies (started with asm2, then tried in the original one) - sorry I can't be of any more help why that happens

[asm.zip](https://github.com/Zolko-123/FreeCAD_Assembly4/files/6411299/asm.zip)

**Comment by Zolko-123** [comment]
good catch, fixed (in the development branch)
