### ISSUE TITLE
Recompute after variable change

### ISSUE THREAD

**Issue by jdorel** [Zolko-123/FreeCAD_Assembly4#194]
# Situation

I am trying to simulate an object changing position, using a variable. For this, I used the variable in the attachment offset (position y) : `-240 * <<Variables>>.transform`.

- When I change `transform` from 0 to 1, nothing change.
- When putting it back from 1 to 0, it acts as if the `transform` was equal to 1.
- Using right-click --> `Recompute object`, the position is the correct (`transform` = 0). 

# Expected behavior
As soon as I change the variable, the objects should be recomputed.

### FreeCAD Version
FreeCAD 0.19.24276

**Comment by Zolko-123** [comment]
this is core internal FreeCAD behavior, Assembly4 cannot change it
