### ISSUE TITLE
Undo during Transform does not update the dragger position

### ISSUE THREAD

**Issue by diniciacci** [Zolko-123/FreeCAD_Assembly4#204]
This is a minor glitch probably worth a small fix.

Steps to reproduce:
1. Assemble two parts
2. Right click on one and select "Transform"
3. Dragger appears to move the Part/Body
4. Use the dragger to move the Part/Body. The Body/Part moves.
5. Select Edit->Undo
6. Part/Body is moved back to it's original position, but the Dragger stays in its current position
7. From now on Dragger use is erratic.

Expected behaviour:
- Dragger position is updated to original position when undo is selected.

**Comment by Zolko-123** [comment]
This is a core FreeCAD issue, not Assembly4 related

**Comment by diniciacci** [comment]
Thanks, sorry for the noise.
