### ISSUE TITLE
Feedback animating a Assembly4 for the fist time.

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#210]
First time using this Workbench. 

I have some feedback using Animation Export Preview

1. I am running on Linux. I cannot save a file with this path `~/myfile.png`. It looks like the `~` path does not work.
2. When "Creating and Saving" images. A popup with the progress open behind the "Animation Export Preview" window. It took me ages to find this thing. Maybe a progress bar on the same window helps more here since this  "Animation Export Preview" does not lose focus. At least on Ubuntu which is my OS.
3. Close button does not work when exporting images only the X button. This is bad since I was having issues 1 and then 2.

**Comment by Zolko-123** [comment]
did you try with the latest version ?
