### ISSUE TITLE
Feature Request - Version Number

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#216]
Hi, I would like to ask to show Assembly 4 version number while displaying this message.

![Screenshot-20210823105207-256x56](https://user-images.githubusercontent.com/1277920/130459163-730f28fb-be5d-4106-b467-4d1f6a9c0bfb.png)

Maybe something like this
```
Activating Assembly4-1.0 workbench.
```

**Comment by Zolko-123** [comment]
good idea

**Comment by Zolko-123** [comment]
done
