### ISSUE TITLE
Insert fastener command doesn't work when diameter is changed

### ISSUE THREAD

**Issue by xoviat** [Zolko-123/FreeCAD_Assembly4#242]
If both the 'fastener' type and 'diameter' is changed, then the insert fastener command fails.

```
09:29:15  At ~\AppData\Roaming\FreeCAD\Mod\fasteners\FSChangeParams.py Line 342
09:29:15  {'sclassname': 'class Base::ValueError', 'sErrMsg': "'#6' is not part of the enumeration", 'sfile': '', 'iline': 0, 'sfunction': '', 'swhat': "'#6' is not part of the enumeration", 'btranslatable': False, 'breported': True}: Inappropriate argument value (of correct type).
```

This may be a fasteners workbench issue?

**Comment by Zolko-123** [comment]
It doesn't actually fail, it produces that error but still works. Anyway, that belongs to the "fasteners" workbench and the error is triggered even when using the "pure" fasteners command. So you might want to report that error in the FreeCAD forum:

https://forum.freecadweb.org/viewtopic.php?f=8&t=11429
