### ISSUE TITLE
Missing image in Tutorial 1

### ISSUE THREAD

**Issue by justinclift** [Zolko-123/FreeCAD_Assembly4#25]
Am going through the first tutorial now, updating some of the wording to match the (guessing here) newer names of some menu options and similar.

On the way through, noticed there's a missing image (_Examples/Tutorial1/icons/Link_Part.svg_) showing a placeholder broken image icon under the *Document "asm_tuto1"* -> *Insert axis* section.

Any chance you have the image somewhere, and it just needs pushing to the GitHub repo? :smile:

**Comment by Zolko-123** [comment]
thank-you, should be fixed now

**Comment by justinclift** [comment]
Yep, it's showing up now.  Thanks @Zolko-123. :smile:
