### ISSUE TITLE
Feature request: automatically add local coordinate system for features, and optionally let user pick them graphically

### ISSUE THREAD

**Issue by QiangF** [Zolko-123/FreeCAD_Assembly4#265]
I have just start learning to use Assembly4 today. It seems all these LCSs are just special direction of a feature. I think manually defining LCS is redundant, and hard to associate with the feature by just looking at its names. In a complex assembly, tens of LCSs on one main part will be hard to manage.  So I am wondering why not just let the user selecting most of the LCS on the actually part feature when needed, of course you can show some graphical aid during selection, like other assembly workbenches, without naming all of them explicitly.

With LCSs only you still got the topological issue. For example if one LCS sits on an edge of a chamfer, and the chamfer is removed later, the relationship is broken. It's the unchanging master sketch that solves the topological naming issue.  That's what missing in the other workbenches. Or make it 3D, add master hidden soild.

Feel free to close this is it doesn't make sense.

**Comment by Zolko-123** [comment]
No, not all features need an LCS. You should use this in reverse: define _first_ the - main - attachment points that your part is going to need, based on its functionality, and _then_ design the geometry around that. You can define, _later_, secondary datums, for screws for example, but they're not going to break the main assembly.
