### ISSUE TITLE
Name for the link is "Body" 

### ISSUE THREAD

**Issue by v-h-giang** [Zolko-123/FreeCAD_Assembly4#271]
After reinstall i got some strange behavior when insert a part to assembly model (ctrl + L) , the "Name for the link" is defaultly set to "Body" . It was "insert file name  +  '_Body' " before. When attaching a part in the assembly, in "Place linked Part" window, the "Attach to :"  list will not change with 3d view selection as before. I must select the attach part from the pop down list. 
Any something changed recently ?

**Comment by Zolko-123** [comment]
For the filename, yes it was changed because it made very long names, and also for some cyrillik languages the filename characters where replaced with _ which was not helpful

for the selection, no, this is not normal, what version are you using ? What OS ?

**Comment by v-h-giang** [comment]
I really like the old way that "name for the link" can automatic set to "filename_Body". I am using Assembly4 for designing and development machine with large amount of parts ( about hundreds) . Every parts have special name and id with its file name (in english).  Its really help if have some checkbox for old way naming , near "Name for the link" . 

About the selection , i am using newest stable version of Freecad (0.19 ) and Assembly4  , windows 10 with newest update. And that "Attach to :" list will change when click to LCS on the part only .  But almost the time , LCS stay in middle  of  Screw hole , on the surface that hard to click or view from outside of complex model .

Thanks for response !

**Comment by Zolko-123** [comment]
I guess the automatic naming should be set in the user preferences. I'll look what I can come up with

**Comment by leoheck** [comment]
I thought you were not into this automagical bs, lol.

![image](https://user-images.githubusercontent.com/1277920/189432977-f40b84bf-4e19-4752-acb4-c8e86aa0edda.png)

https://github.com/Zolko-123/FreeCAD_Assembly4/issues/344
