### ISSUE TITLE
BOM not working after updating assembly4 to version 0.11.4

### ISSUE THREAD

**Issue by markbil** [Zolko-123/FreeCAD_Assembly4#272]
hi, thanks for the great work on assembly4! I am designing my kitchen cabinets in freecad, and since I updated assembly4 to version 0.11.4 from an older version through the addon-manager, the BOM feature (Menu => Assembly => Create Part List) does not seem to work any longer. in the older version a popup window would appear with a list of all my Part names (kitchen cabinet panels) and their dimensions, i.e. something similar to "Top Panel: 600 x 18 x 450, etc.". Now when I execute the same function I receive an empty popup as pasted below... Also the report view throws "10:28:40  3634.66 Selection.cpp(1649): Object not found". I changed nothing but updading assembly4 to the latest version...
Am I doing something wrong or is this a bug? Thanks for your help!
![bom_assembly4](https://user-images.githubusercontent.com/610585/142836058-d28fc193-5464-48fd-a35b-ef53c8626569.png)

**Comment by Zolko-123** [comment]
Thank-you for reporting, I'll have a look at it. The BOM functionality is mostly implemented by @FarmingSoul

@FarmingSoul : could you have a look at the issue at hand here ?

**Comment by markbil** [comment]
@Zolko-123 great, thank you!

for what it's worth, I created the following macro which prints my part list and their dimensions as expected. Using BoundBox **some** of the dimensions are very slightly off (like 0,00000001), which I fixed with rounding. Not sure why and whether there is a better method to get the exact dimensions for each part...

```
doc = App.ActiveDocument
for object in (doc.findObjects("PartDesign::Body")):
    print (object.Label2, end=": ")	
    if hasattr(object, "Shape"):
        bbc = object.Shape.BoundBox
        zl = round(bbc.ZLength,3)
        yl = round(bbc.YLength,3)
        xl = round(bbc.XLength,3)
#       print (str(bbc.ZLength), str(bbc.YLength), str(bbc.XLength))
        print (zl, yl, xl)
```

**Comment by FarmingSoul** [comment]
@Zolko-123 , @markbil 
Sorry this 3 weeks i work a lot.
sorry for the inconvenience and thank you for the return. 
In the new version the BOM fields are configurable. 
explanation :

Select a part
![1-part select](https://user-images.githubusercontent.com/65253765/144839275-00177a61-8b62-4238-83c1-a4ed14b4a484.png)

Click on Edit Part Information
![2-click infoPart](https://user-images.githubusercontent.com/65253765/144839286-00d131f7-114c-4e38-be2b-7a99009bd4a1.png)

Click on config
![3-click config](https://user-images.githubusercontent.com/65253765/144839287-99311e01-a9b5-4241-a570-0d0bf99c188c.png)

in this column you will find the default names. 
If you stay with the mouse on a field a tooltip opens to indicate the principle of this autofield.
![4-default data](https://user-images.githubusercontent.com/65253765/144839288-01a6fb87-8182-4ac1-9b0a-467cbd05aa19.png)

here you can customize the name of the field
![5-user data](https://user-images.githubusercontent.com/65253765/144839289-4bc068cd-fb9e-404f-b16a-9832f23d2071.png)

here you can decide if you want to use this autofield
![6-active](https://user-images.githubusercontent.com/65253765/144839291-5c76a816-a1ea-471c-8f9b-bb57d6a5c92b.png)

this function is currently not present
![6-order](https://user-images.githubusercontent.com/65253765/144839294-b5b211d7-ecc7-4519-85e1-166646023849.png)

you can add fields to be filled in manually in Edit Part Information
![7-custom manual field](https://user-images.githubusercontent.com/65253765/144839296-c161d991-cd96-4c1c-95d1-b827a7ab175c.png)

Your request does not have the area to be managed by the current autofield so I will integrate your macro and a new autofiled will be present in the next version of ASM4.
Here is the file I will modify.
![8-add autofield](https://user-images.githubusercontent.com/65253765/144839297-f5e68b8a-2ff8-48d3-9e42-f1390920c747.png)

here there is a typical explanation for creating your own autofield
![9-explanation](https://user-images.githubusercontent.com/65253765/144839285-a2217d82-2d4b-4d29-b520-8685b24737cb.png)

Have nice day

**Comment by FarmingSoul** [comment]
![10-issue](https://user-images.githubusercontent.com/65253765/144902563-c7c43c25-ba15-4fed-961f-d67560c0b5c2.png)

fix

you can use this file :

https://raw.githubusercontent.com/Zolko-123/FreeCAD_Assembly4/0e872345049d72f58f84fee6df03aa85640a614f/InfoKeys.py

and the next Update of ASM4 have this fields .

Nice Day

**Comment by robertlinn0423** [comment]
I'm experiencing the same empty Bom panel when clicking the PartsList button as markbill shows on Nov. 22, 2021.  I'm running these versions:

- O/S: Linux Ubuntu 21.10
-  FreeCAD 0.19 revision 24366
- Assembly 4: 0.11.11
When I click the Ok button from the Parts List/BOM panel the console shows '6.82e-07 Selection.cpp(1649): Object not found'.
I've followed the tutorial from here: https://github.com/Zolko-123/FreeCAD_Assembly4/blob/master/Examples/ConfigBOM/README.md several times always with the same result 'Selection.cpp(1649): Object not found'

Any thoughts or help is appreciated.
Thanks
Bob

**Comment by leoheck** [comment]
@robertlinn0423 the development branch has an improved BOM, I invite you to check if it works for you.

**Comment by Zolko-123** [comment]
BOM has been updated recently, please see #341
