### ISSUE TITLE
Bug in "Create symmetric of part"

### ISSUE THREAD

**Issue by FreeCutter** [Zolko-123/FreeCAD_Assembly4#277]
Pockets based on sketched circels became quads in the mirrored part (?).

![mirrored part](https://user-images.githubusercontent.com/53740858/144926168-7d15ed7c-0a36-456a-b829-add7e5503595.png)

**Comment by Zolko-123** [comment]
yes, the symmetry tool is not very good

**Comment by FreeCutter** [comment]
okay, thank you. Closed.
