### ISSUE TITLE
Can't use variable link part as parent part 

### ISSUE THREAD

**Issue by giannissc** [Zolko-123/FreeCAD_Assembly4#278]
A current limitation of variable link part is that you can't attach other components do them when creating an assembly. Is that a known limitation that you just haven't had the chance to fix or is there  something about variable link parts that make this impossible?

**Comment by Zolko-123** [comment]
yes, this is a current technical impossibility.

**Comment by Zolko-123** [comment]
because variant links are made with temporary documents, and thus it's impossible to know in advance the name of that temporary document
