### ISSUE TITLE
"Place linked Part" - translate parts x,y,z inputs do not allow the use of variables [improvement]

### ISSUE THREAD

**Issue by cons0l3** [Zolko-123/FreeCAD_Assembly4#287]
Scenario: Assemble a corpus (=box) with 5 sides and a lit/door. Left/Right, Top/Bottom, Front/Back are three parts in the library. Each part has one LCS (its origin). When assembling I have to rotate and translate the sides. (or I could place an LCS for every corner of each part). I have to translate by corpus width/height/depth (+/- the material thinkness). The width, height, depth and thickness are setup as variables.

Requirement: Make it possible to use the variables in the "Place linked Part" dialog directly

Work-around: set abitrary constant numbers for the translation, finish the placement, replace the constant number with the variable in the placement under the properties of the placed part in the assembly-tree.

**Comment by Zolko-123** [comment]
yes. Use work-around
