### ISSUE TITLE
`Create Part List` don't add parts that are inside a Group

### ISSUE THREAD

**Issue by hasecilu** [Zolko-123/FreeCAD_Assembly4#310]
While creating the BOM for the assemblies I notice that only the Parts that are directly attached to the main `Assembly Part` appear in the BOM but ignores Parts inside a Group.

If you try to organize the Parts in the tree this is a problem, specially with a lot of Parts.

**Comment by leoheck** [comment]
@hasecilu development branch has a better BOM, could you check if it works for you?

**Comment by Zolko-123** [comment]
BOM has been updated recently, please see #341
