### ISSUE TITLE
Change the Blue Body Appearence from the Yellow Body.

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#328]
I was experimenting with Assembly4. 
Something that I don't like, is that I have to expand Yellow Bodies in order to change the opacity of the objects.

The Yellow body has the Appearance menu when right-clicking on it. But the properties it opens are greyed out.
Is there a way that the Yellow Bodies could bypass the Appearance menu to the Bodies inside of it?

**Comment by Zolko-123** [comment]
Yellow Parts and blue Bodies are standard FreeCAD objects (containers) so there is nothing that Asm4 can do to change their behavior.
