### ISSUE TITLE
Multiple Animations / Explode Assembly

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#329]
Is it possible to have multiple animations on Assembly4?

Or is it possible to create the exploded assembly with this workbench?

Maybe the exploded assembly could be something we could get out-of-the-box, where a sliding button would control the space between parts separating them from each other like the universe was expanding around them splitting the whole assembly apart.  =)

A similar thing is found on Grabcad Workbench

Before expanding
![image](https://user-images.githubusercontent.com/1277920/185230315-03e74ffd-5666-4a9b-b95a-4d17c6bce508.png)

Expading the whole thing...
![image](https://user-images.githubusercontent.com/1277920/185230375-e40ae67b-db71-4332-a773-f7234f7b86e1.png)

**Comment by Zolko-123** [comment]
Exploded assemblies can be done with configurations: first, make a default configuration with all parts in their correct location. Then, move and/or hide parts as wished by adjusting the AttachmentOffset property of each part. You can then create a new configuration based on this state. As opposed to an exploded assembly, you can create as many states as you wish, showing/hiding parts, and/or offsetting parts from their assembled position. 

The goal of the configuration manager is to create user instructions for assemblies, which includes, but is not limited to, exploded assemblies

**Comment by leoheck** [comment]
This looks interesting. Do you have a demo/example showing this workflow? I am using Assembly4 for 2 days only.

**Comment by Zolko-123** [comment]
no, sorry

**Comment by leoheck** [comment]
Indeed, configurations are awesome. Thanks for the instructions above.
