### ISSUE TITLE
Part Information GUI

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#335]
I am trying to understand this screen. 

![image](https://user-images.githubusercontent.com/1277920/185516701-6b014166-9f95-45ea-b3ac-f7c2749cc454.png)

What are these fields? They are named, but there is a command/code/random strings there.

I mean, by your answers here on Github you are an experienced English speaker, a Master compared with me. 
Now, when I see those kinds of things in a user interface I don't understand a word. It looks like it was implemented quickly.

Can we have meaninful labels on these items?
Also, could we have tooltips explaining what are we filling there?

Also, what are these icons? What they do? Config what? re-init? auto-fill? 
Can we have all text with the same style like, Title Case, or First letter uppercase?

Maybe it would be interesting to polish the text found here too. 
![image](https://user-images.githubusercontent.com/1277920/185516975-f20bc5a0-7064-413d-b803-33e8f681e1ba.png)

Otherwise, we are going to have a table that is not quite good to understand
![image](https://user-images.githubusercontent.com/1277920/185517040-ac4e6cb7-55f1-4202-801b-74b5f0e438fe.png)

**Comment by Zolko-123** [comment]
_BoM_ and _PartInfo_ have been written and re-written by several people, most if the time for their own restricted usage. If you can come up with a good general approach similar to what is used in the industry, that would be very useful

**Comment by leoheck** [comment]
I am not asking to re-write anything. I am just asking a bit of info. I have no idea how these fields are. Do you have any documentation of the Part Info? I could not find any.

**Comment by leoheck** [comment]
LOL
