### ISSUE TITLE
Asm4_NewPart with multiple Bodies

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#336]
Hi Zolko, is it possible to have more than one Body inside the `Asm4_NewPart`?
I have a Part with 3 Bodies but I am getting the following message. I don't know what to do. Is this an error and has to be fixed? How should I proceed?

```
20:00:52  PartDesign::CoordinateSystem: Link(s) to object(s) 'Pocket023' go out of the allowed scope 'LCS_Connector'. Instead, the linked object(s) reside within 'Part_2 Part_2'.
```

**Comment by Zolko-123** [comment]
> How should I proceed?
> ```
> 20:00:52  PartDesign::CoordinateSystem: Link(s) to object(s) 'Pocket023' go out of the allowed scope 'LCS_Connector'. Instead, the linked object(s) reside within 'Part_2 Part_2'.
> ```
Issues here are for listing and solving software bugs. For general usage help please address your questions to the FreeCAD forum : https://forum.freecadweb.org/viewforum.php?f=3

**Comment by leoheck** [comment]
This ![image](https://user-images.githubusercontent.com/1277920/186703616-0dd1c9c2-3ff0-4be8-b696-c0303948b03c.png) is definitely a question for here since the README does not have such info. And there is no info related to that, here on this repo.
