### ISSUE TITLE
It is better to have a filter that is case insensitive when Inserting a Part

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#338]
It is always good to have case-insensitive filters AND, match substrings, instead of just matching the beginning of a string.
![image](https://user-images.githubusercontent.com/1277920/187310178-623f4ec6-a6d8-4038-a28e-3053ab357a54.png)

**Comment by Zolko-123** [comment]
you're right. Can you provide a code example that would do that ?

**Comment by leoheck** [comment]
Sure, here it is. 
https://github.com/Zolko-123/FreeCAD_Assembly4/pull/343

**Comment by Zolko-123** [comment]
Thank-you. This is now included in the latest release
