### ISSUE TITLE
Keep the last used Parent already in the "Place linked Part" window

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#344]
Something that I like is when adding a new Part, the previous part is already selected. This is good when adding multiples of the same part, but it also good to keep track of the order of the parts being imported.

Now, the same thing could be added to the "Place linked Part" window. The last used Parent could be also selected by default there. 

What do you think?

**Comment by Zolko-123** [comment]
Nothing. Might be good for some people and annoying for others. I don't like too much automagical functions

**Comment by Zolko-123** [comment]
well, no, but thanx for the propasal
