### ISSUE TITLE
Body: object is not allowedTraceback (most recent call last):

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#345]
I am getting this issue when adding a "New Model" in a file that already has "New Part" models in it. 

I am using parts inside of this file in another file. But now I would like to have a "New Model" here in this current file, assembling them locally. 

![image](https://user-images.githubusercontent.com/1277920/189486928-4ab4683a-ea64-42fb-b6ba-facc34859fa9.png)

**Comment by Zolko-123** [comment]
the problem seems to come from some magic that part-o-magic is doing. I've never used that, I invite you to investigate the issue further down to the core and report back here

**Comment by leoheck** [comment]
Ah, really? I am going to remove it, then, to check if this happens again. This WB is too verbose even if I am not using it. I used it to replace a Sketch that was problematic. But I don't use it anymore. It makes a lot of sense. I  going to close this issue, If I see something like this again, I will reopen it, then. Thanks @Zolko-123
