### ISSUE TITLE
There are still something strange with fasteners

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#347]
Working with fasteners, and there is something that is still not working. 

I am using the lates Assm4 0.12.4

- I cannot change the parameters of the fastener while creating it.
- I cannot change its name/label 
- I cannot update parameters while they are linked

![image](https://user-images.githubusercontent.com/1277920/189492159-d7db1b94-1858-4591-8306-94d041813d6e.png)

Here, the m4-30 in the objects tree, is the m6 in the parts list.

**Comment by leoheck** [comment]
If I put it inside the Part, it shows in the list
![image](https://user-images.githubusercontent.com/1277920/189492378-a2cd0a21-eee2-4f60-9a9c-85626b6f7f35.png)

**Comment by leoheck** [comment]
Should I place fastners inside a "Part" or should I use them as they are, if adding them from Assembly4 toolbar?

**Comment by Zolko-123** [comment]
please use the FreeCAD help forum

**Comment by leoheck** [comment]
Are you de developer or just a puppy?
