### ISSUE TITLE
Adding the LCS in the Model does not end in the right place

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#351]
I am adding an LCS in the Model, to use it when adding it as a Part in another assembly. When I click on a feature in the model (lets say, a circle, it places the LCS where the Part is, and not where the Part is inside the Model. 

It is placing the LCS in the top right of this image, where it should place in the center of the selected circle

![image](https://user-images.githubusercontent.com/1277920/189503661-697c5d9a-c233-4dd0-ba49-a47aad0ceb98.png)

If I turn the part visible, you are going to see that the LCS is where the part is, but not where the part is relative to where it was placed in the Model.

![image](https://user-images.githubusercontent.com/1277920/189503689-dbf0cc52-1b40-41b1-a236-fedb796c4878.png)

**Comment by leoheck** [comment]
Even using Hole Axis, it is not possible to place an LCS easily in the Model for reusing the Module externally, in another Assembly.

**Comment by Zolko-123** [comment]
this is normal behavior, you're not using it correctly, please ask for help in the FreeCAD Help forum

**Comment by leoheck** [comment]
I asked, they dont offer any help. How is the correct use of it?
