### ISSUE TITLE
Missing Fastners

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#357]
Hi @Zolko-123 there are some fasteners missing in the Asm4 Fasteners button and from the "Change Fasteners parameter"  like spacers, for instance. 

What was the reason behind using Assm4 spacers instead of the ones from Fasteners WB?

This is the BOM listing the one I am using from the Fasteners WB.
![image](https://user-images.githubusercontent.com/1277920/192098095-f36dc0d6-bd30-488a-a187-83189479ae62.png)

**Comment by Zolko-123** [comment]
There are no Asm4 spacers

**Comment by leoheck** [comment]
Yes, this is what I am saying. Fasteners WB has Spacers. Asm4 doesn't. Can we have Spacers in the Asm4 too?

**Comment by Zolko-123** [comment]
Fasteners is a standalone WB with its own development pace, some of them – the most common ones – are included in Assembly4 WB for convenience. For the others please use the Fasteners WB directly, the resulting parts are usable in Asm4.

**Comment by leoheck** [comment]
> For the others please use the Fasteners WB directly, the resulting parts are usable in Asm4.

Ah, that's it then. I thought Asm was doing customization of something. This is good, thanks.

**Comment by Zolko-123** [comment]
the only customisations are the colors

**Comment by leoheck** [comment]
yeah, and this tells the ures the fasteners are different, which is not true.
