### ISSUE TITLE
Attached To: LCS Missing after rename

### ISSUE THREAD

**Issue by bernard01** [Zolko-123/FreeCAD_Assembly4#360]
The attached zip file contains five files that form a nested assembly. Five files because I understand one file can only hold one model. Which I think is a good limitation because complexity and confusion could get out of hand otherwise.

My task is the following: Get all attachment LCS pairs aligned in all 3 axis directions, congruent.

For that, I need to have understanding of the LCSs because it seems I get confused easily with this.

I remember that earlier, I renamed in Z_AxisLinearArm.FCStd an "Attached To" LCS from LCS_A_Axis_RotationalArmPart to LCS_A_Axis_RotationalArmAssembly (I hope I remember this correctly).

The rename apparently succeeded in the Model view, and LCS_A_Axis_RotationalArmAssembly is visible there.

But when I focus on the linked model A_Axis_RotationalArm under the model of Z_AxisLinearArm.FCStd, then in the Property Sheet the "Attached To" value is still old:

External link in model of Z_AxisLinearArm.FCStd

Link
    Linked object: A_Axis_RotationalArm#Model

Assembly
    Attached By: #LCS_A_Axis_RotationalArmParent
	Attached To: Parent Assembly#LCS_A_Axis_RotationalArmPart ######## - This is missing.
	It should actually be attached to Parent Assembly#LCS_A_Axis_RotationalArmAssembly

I am now confused because the Property Sheet is the only orientation I have to discover the structure of the assembly. That means I cannot complete my task.

If I wanted to write a program that validates the structure of an assembly model, then I would not know what exactly that program would be looking at - meaning I would not know whether that program is tricked that everything is correct when in fact something is broken.

I hope that the files in attached zip file
[RobotAssembly.zip](https://github.com/Zolko-123/FreeCAD_Assembly4/files/9640339/RobotAssembly.zip) 
help clarify the situation, and that they form a test bed to find a solution for this kind of problem.

[code]
OS: Windows 7 Version 6.1 (Build 7601: SP 1)
Word size of FreeCAD: 64-bit
Version: 0.20.29177 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 68e337670e227889217652ddac593c93b5e8dc94
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.2
Locale: English/New Zealand (en_NZ)
Installed mods: 
  * Assembly4 0.12.3
[/code]

**Comment by Zolko-123** [comment]
Please use the dedicated FreeCAD forum for help: https://forum.freecadweb.org/viewforum.php?f=3 . 

Also, please suppress the backup files when including files for download.
