### ISSUE TITLE
Linked Object

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#364]
I have to update the linked object, but the Model does not show in this Window here for some reason.
Are you aware of this? 

![image](https://user-images.githubusercontent.com/1277920/193037867-98a9b410-74a4-4445-adfa-050c956d6641.png)

**Comment by leoheck** [comment]
Is there any other way to update a broken link?

**Comment by leoheck** [comment]
I am looking for a way to change this #Fan_80mm to #Model
![image](https://user-images.githubusercontent.com/1277920/193040117-08874a43-a0fc-4ed3-8029-11395eb92cd6.png)

**Comment by Zolko-123** [comment]
If you select the broken link, and click the function "insert link" then it should give you the option to choose another target object to be re-linked.

**Comment by leoheck** [comment]
The "insert link" is the Import Part?

**Comment by leoheck** [comment]
Ah, it is, indeed. It is written in the Tooltip, thank you.
