### ISSUE TITLE
Configuration not being updated all the time

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#365]
For some reason, the configuration does not work all the time... when I am playing around with my configurations there are moments where the design/view is not updated. I could not create a process to reproduce it yet, but there are times that this stops working.

**Comment by Zolko-123** [comment]
If there are no new updates on this I close the Issue

**Comment by leoheck** [comment]
Sure, let's close this. I could not reproduce it since I am clicking just once in a while on this button.
