### ISSUE TITLE
Unkown bug

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#367]
I am still reviewing the BOM thing but I found a little bug. Not sure what it is but I am not touching this file. 

```bash
➜  Assembly4 git:(development) ✗ Unhandled unknown exception caught in GUIApplication::notify.
Traceback (most recent call last):
  File "/home/lheck/.local/share/FreeCAD/Mod/Assembly4/./AnimationLib.py", line 129, in IsActive
    def IsActive(self):
<class 'KeyboardInterrupt'>: <unknown exception data>

```

**Comment by leoheck** [comment]
Feel free to close this if it is not important, I am just sharing because it happened now, all of the sudden.

**Comment by Zolko-123** [comment]
If there are no news on this I close this Issue

**Comment by leoheck** [comment]
Yeah, it did not happen again.
