### ISSUE TITLE
Cannot enter more than 2 decimals in the variables dialog box 

### ISSUE THREAD

**Issue by Jeanmimi0168** [Zolko-123/FreeCAD_Assembly4#382]
Variable creation dialog box doesn't allow to enter more than 2 decimals, but in the property list you can enter more than two decimals.

Version 0.12.4 08/11/2022

**Comment by Jeanmimi0168** [comment]
Seems to be due to default value of QDoubleSpinBox.decimals that could be changed by QDoubleSpinBox.setDecimals(int).

**Comment by Zolko-123** [comment]
good catch: do you know how to do a PR for that ?

**Comment by Jeanmimi0168** [comment]
Tried it, tell me if I made it right.
Just CAD user with some background of python.

**Comment by Zolko-123** [comment]
looks good. But can you please make the PR against the development branch ? Also, 6 digits ... you're planning ahead !

**Comment by Jeanmimi0168** [comment]
I needed to scale about a bitmap measurement, and there was more than that!
I try to change the PR to dev branch

**Comment by Jeanmimi0168** [comment]
Did not found how to change branch, just closed the PR and opened a new one on dev branch.

**Comment by Zolko-123** [comment]
thnaks, can-you please close this issue now ?

**Comment by Jeanmimi0168** [comment]
Thanks!
