### ISSUE TITLE
can not specify arbitrary symmetry plane in creating symmetric part

### ISSUE THREAD

**Issue by QiangF** [Zolko-123/FreeCAD_Assembly4#383]
The "create symmetric of part" should really just lik "create circular array", let the user select the symmetry plane, and make it work also for sub assemblies.

**Comment by QiangF** [comment]
Tutorial 3 might be easier and cleaner with the lattice workbench.
https://github.com/DeepSOIC/Lattice2

**Comment by Zolko-123** [comment]
You're right, but it's more complicated to do
