### ISSUE TITLE
Editing LCS causes FreeCAD to crash

### ISSUE THREAD

**Issue by sslupsky** [Zolko-123/FreeCAD_Assembly4#40]
When using the Assembly4 workbench, if you create a model LCS and then attempt to edit it (right click and select "Edit datum"), FreeCAD crashes when you click OK.

OS: macOS Mojave (10.14)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.19323 (Git)
Build type: Release
Branch: master
Hash: 1b198453b8eb6aa2eaca4e4be4b49fee74e9de6e
Python version: 3.8.1
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/Canada (en_CA)

**Comment by Zolko-123** [comment]
Yes, this is a known FreeCAD bug:

https://tracker.freecadweb.org/view.php?id=4258
