### ISSUE TITLE
XYZ translation is not accepting floating numbers and formula

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#402]
I cannot put floating numbers. 
I am trying with . (US format) and with (Brazilian format)
None of these work. 

The dot is added, but it is not possible to add values after that.

This field does not accept equations using the "=" shortcut.

![image](https://user-images.githubusercontent.com/1277920/219875528-d0d2b90b-8d3c-49de-9e03-9b09646f5c44.png)

I imagine that Freecad has a special input field for this kind of thing that could be used here, easily.

**Comment by Zolko-123** [comment]
it's probably a setting in your locale, `.` –vs– `,` , on my computer it works

> I imagine that Freecad has a special input field for this kind of thing that could be used here

yes, I think

> easily.

If it's "_easy_" for you thank-you for submitting a PR

**Comment by leoheck** [comment]
Yesterday I installed a Theme for the first time. Then this started to work again. 

DarkPro
![image](https://user-images.githubusercontent.com/1277920/220118473-3258fdc6-8d8e-4adf-8fc3-5e209735b40d.png)

Classic theme
![image](https://user-images.githubusercontent.com/1277920/220118551-ce114b44-692a-4307-983c-27f823b277b4.png)

Freecad behaves so badly sometimes.
