### ISSUE TITLE
Parts that start with a number in their name are not shown properly in the pick list in Assembly4

### ISSUE THREAD

**Issue by PAS-DRAFTER** [Zolko-123/FreeCAD_Assembly4#418]
[https://forum.freecad.org/viewtopic.php?p=671539#p671539](url)

As [beischer](https://forum.freecad.org/memberlist.php?mode=viewprofile&u=36335) shows in the Assembly 4 chain, if you have a part name that begins with a number (ex:   2 Part, 3 Part, etc.) when you go to try and pick them from the Insert Part Dialog, the names are not displayed correctly and it is difficult to find the right one.

I think this issue is pretty obvious if you try it, but I have added a sample file to the chain to show the issue.

![InsertPart](https://user-images.githubusercontent.com/115263312/228146039-a2860057-b0b2-4c33-b471-bfedfe35d128.png)

**Comment by Zolko-123** [comment]
This is a known FreeCAD issue, not Asm4 related
