### ISSUE TITLE
Question / Feature Request: allow use of "Part" objects in Assembly Model

### ISSUE THREAD

**Issue by BloodyRain2k** [Zolko-123/FreeCAD_Assembly4#419]
There's a possibility that I'm using the WB wrong, but it is almost working "as intended" as far as I can tell.
At the very least did nothing break. Even reloading the file and restarting FreeCAD was no issue.

![image](https://user-images.githubusercontent.com/1014362/228922776-40f4e674-7daf-415f-b0bd-7eda288384dd.png)

The reason I grouped the linked parts in the "Part" object, was simply because I didn't want to make an identical circular array for each part. All I did was set them up outside of it, all being direct children of the "Model" at that time. Most are attached to a LCS of the "Arm".
After that, I simply dragged them into the "Part", only using it as a container.
I would've just created a "Part" in the Parts group instead, but I couldn't figure out how to attach the linked bodies where I wanted them...

But the setup as shown, is completely fine, including animating, reloading etc. Until something needs to be adjusted...
Because the WB does not yet support more than one "Part", likely because the main assembly is also one, none of the linked parts inside the "Part" can be adjusted with the "Edit placement" function.

No LCS inside the grouping "Part" is showing up in the dialog, not even the one directly inside it.
And if any part of, or that "Part" itself, are selected, it complains about an invalid object being selected.

I am aware that there's limited support for "sub assemblies", but I can't see an obvious issue with the systems in place, in this one use case at least. Only the UI for making changes to the LCS' attachments doesn't want to work with it yet.
Everything else works completely fine. Although it might be that that is only the case, because I'm using the Link version of FreeCAD.

And to finally get to the actual point: it would be nice if the "Edit placement" function could work for such "sub assemblies".

**Comment by Zolko-123** [comment]
This is not at all how to use Parts and sub-assemblies. Please use the FreeCAD forum for help
