### ISSUE TITLE
Assembly4 0.50.x shows tooltips in status bar as raw HTML

### ISSUE THREAD

**Issue by neildarlow** [Zolko-123/FreeCAD_Assembly4#426]
Versions 0.50.0 and 0.50.1 of Assembly4 display the tooltip content also in the status bar with surrounding HTML paragraph tags for some, but not all, toolbar buttons.

Also there seems to be inconsistencies in the tooltips themselves. Some have blank likes around the descriptions (before the internal command name) while other's don't. This seems to be also related to the HTML paragraph tags.

**Comment by Zolko-123** [comment]
Thanx, I'll have a look

**Comment by neildarlow** [comment]
Thank you. I only reported this because it's the first time the visual presentation of Assembly4 has been anything other than excellent.

**Comment by Zolko-123** [comment]
This is a [general FreeCAD issue](https://forum.freecad.org/viewtopic.php?t=77657), nothing that Asm4 can do about. I invite you to weight-in on the forum if you think it's worth it
