### ISSUE TITLE
Missing toolbar icons (Show/Hide LCS)

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#434]
Hi Zolko, I've noticed that 2 icons have disappeared from the toolbar. They are the `Show/Hide LCS`. Is this intentional or it was a mistake? I miss the icon to `Hide LCS`

**Comment by leoheck** [comment]
I thought I might have introduced this issue, but the history of my latest changes tells me it was like that since before of my changes.

**Comment by Zolko-123** [comment]
people have complained about it, and I don't know when it was removed. I'll put it back

**Comment by Zolko-123** [comment]
I tried with ShapeBinders, and it works too, but your solution is much much faster.

**Comment by Zolko-123** [comment]
Is back in the development branch

**Comment by leoheck** [comment]
Thanks you
