### ISSUE TITLE
Asm4 find objects out of the Parts folder

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#438]
Not sure if this is an issue, just reporting since I think this looks off. Please, close this, if it is not an issue. 

I was not expecting to see the Housing-Top, Housing-Bot available

![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/1277920/64d77e01-ab43-4acf-bbb6-7964f4c0bb5e)

**Comment by Zolko-123** [comment]
yeah, always this Folder things: some people wanted to be able to organise the tree with folders, so now folders are there and visible. But that also means that they're visible for all folders because Asm4 can't know in advance which folders are to be used or not.

I'm closing the issue
