### ISSUE TITLE
isAssembly is checking if the model name is Assembly

### ISSUE THREAD

**Issue by leoheck** [Zolko-123/FreeCAD_Assembly4#439]
Hi Zolko, I just saw this method above from Asm4_Libs.

```python
def isAssembly(obj):
    if not obj:
        return False
    if obj.TypeId=='App::Part' and obj.Name=='Assembly':
        if hasattr(obj,'Type') and obj.Type=='Assembly':
            return True
    return False 
```

I was using this function to check if something is an Asm4 assembly. But it limits to something that is named Assembly. 

Is it important to make this test?

I would prefer to name the car I am assembling "Wheel" instead of "Assembly" which makes more sense when assembling a Car than I can add multiple "Wheels".

**Comment by Zolko-123** [comment]
Yes, it is important to name it "_Assembly_" to guarantee that there is only 1 assembly per file. 

What I do is to set the _Label_ to the name I want, and this is visible in the tree. Wouldn't that work for you ?

**Comment by leoheck** [comment]
Ah, true, makes sense. I made a mistake confusing Name Label. I was having some issue and I tough it was because of that. I will use it to check if it works now with the makeBom working better.
