### ISSUE TITLE
Incompatability with Path workbench.

### ISSUE THREAD

**Issue by IamTheCarl** [Zolko-123/FreeCAD_Assembly4#441]
Hello, I created a [thread on the forum](https://forum.freecad.org/viewtopic.php?p=684794#p684794) on this awhile ago in hope of getting more insight as to if this issue should be opened here or in the main FreeCAD repository.

I never got an answer so I made my own guess that it should be opened here.

The bug is explained in the forum thread. I think it would be redundant to copy that all over here but I can if that's preferred.
I have found a workaround for the moment, which is to just copy the parts into another file and delete all local coordinate spaces before creating a job.

**Comment by Zolko-123** [comment]
on the [thread of the forum](https://forum.freecad.org/viewtopic.php?t=78675) your FreeCAD version shows that you use LinkStage daily:

`Version: 2023.521.0.14555 (Git shallow) AppImage`

Do you confirm ?

**Comment by Zolko-123** [comment]
None of those errors seems Assembly4 related

**Comment by Zolko-123** [comment]
As it looks, Path workbench only works for single solids, therefore it's indeed not compatible with a full assembly. It is, however, compatible with an assembly of 1 part, so it's not an Asm4 issue. 

On the other hand, it's not quite clear what a Path WB should do for complex assemblies ....
