### ISSUE TITLE
Part Not Rotating Correctly

### ISSUE THREAD

**Issue by jmb-555** [Zolko-123/FreeCAD_Assembly4#445]
https://youtu.be/7QVqKXjXS3g

This happens several times every time I try and assemble something. In the video, the x axis button and the z axis button both rotate the part about the same axis.

**Comment by jmb-555** [comment]
I'm trying to point out the fact the two buttons rotate the part about the same axis. The buttons were intended to rotate the part about different axes. This appears to be a bug. It should be visible in the video link.

**Comment by Zolko-123** [comment]
Can you please try to use another datum object as a Point for the placement ? If I remember correctly, a Point doesn't have all the DoF as an LCS (3 -vs- 6).

**Comment by Zolko-123** [comment]
no news
