### ISSUE TITLE
You cannot have a variable named like one of the supported measurement units.

### ISSUE THREAD

**Issue by madhead** [Zolko-123/FreeCAD_Assembly4#447]
Imagine having these variables in an assembly:

![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/577360/dff4ce3b-9f57-4fb9-a2e0-772f97da4eb6)

If you try to use some of them, the expression parser will fail:

![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/577360/88b633fe-47ac-481d-a68d-638c3820534d)
![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/577360/7288440f-f4b7-468b-8290-21ba93d38d4a)

While the other works perfectly:

![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/577360/c2a20b1b-203a-4796-97f4-bd64b8253cde)

It seem like the expression parser doesn't like any variables or aliases to be named like one of the [supported units](https://wiki.freecad.org/Expressions#Units). I guess it happens somewhere near the `ExpressionParser::isTokenAUnit`.

It would be good to see a cleaner explanation in this case, other than the "Failed to parse expression".

**Comment by Zolko-123** [comment]
you can't be serious in claiming this

**Comment by madhead** [comment]
@Zolko-123, excuse me?

This is what really happens and I had to read the source code (the original FreeCAD) to understand why my `t` variable (which is a suitable name for a time, for example) just does not work. This is frustrating. And I imagine not every FC user would be able to understand.

This issue could not happen, for example with Spreadheets, as they just don't allow a user to use units as aliases. But the A4 spreadsheet allows users to create variables that could not be referenced later. I don't understand why it's an invalid issue.

**Comment by Zolko-123** [comment]
> I don't understand why it's an invalid issue.

tough, you have a lot to learn

**Comment by madhead** [comment]
Then maybe link to a doc where it's described?

**Comment by Zolko-123** [comment]
A doc that says that " _kg_ " is a reserved variable name ? If you're such an ignoramus please don't even try to use Assembly4

**Comment by madhead** [comment]
The only doc I found and linked above says (it's not a A4 doc, though)

>> If you have a variable whose name is that of a unit you must put the variable between << >> to prevent it from being recognized as a unit. For example if you have the dimension Sketch.Constraints.A it would be recognized as the unit ampere. Therefore you must write it in the expression as Sketch.Constraints.<<A>>. 

That trick doesn't work with A4.
![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/577360/4ba512ce-3d57-4e74-90e0-aa34d2b3e60c)

And while using a `kg` may sound idiotish to you, there is no reason not to make a product more user-friendly if it is possible.

**Comment by Zolko-123** [comment]
t ≠ kg

**Comment by madhead** [comment]
Well, FC recognizes `t` as a tonne:

![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/577360/4fa8e13e-c378-4684-b439-58afc45801a0)

Here is a link to their parser or so: https://github.com/FreeCAD/FreeCAD/blob/79a31d7483e78d3facf6c58fd6479165819c6776/src/App/ExpressionParser.l#L212-L213

So, `t` is a unit too. Just like many other letters and combinations like `N` or `A` or others.

**Comment by madhead** [comment]
And in my original issues there were both. Both `kg` and `t, and `test`. Just to demonstrate the issue.

**Comment by madhead** [comment]
`oz`, not being a SI init, though, would not work as a variable too.

**Comment by madhead** [comment]
Something like #448 might prevent this class of exceptions and make your workbench a little bit less frustrating.

**Comment by Zolko-123** [comment]
Merged #448 , after all it's not a bad idea, thank-you.
