### ISSUE TITLE
Q/FR: How do I re-access the "place linked part" dialogue?

### ISSUE THREAD

**Issue by LibrarySeph** [Zolko-123/FreeCAD_Assembly4#456]
> Today is my first day messing around with Assembly 4. Please consider this onboarding user testing, I'm clearly not an expert. Maybe someday I will be, but I'll only ever be a novice once.

I wanted to modify an existing assembly attachment, and couldn't find a way to open the original menu:

![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/131182110/cdc2629c-9fad-44bd-b679-886418c4d09f)

I did find the menu below, but it is not as easy to navigate:

![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/131182110/abba5cb8-d2f4-4e44-bff1-8d166f42a42f)

### FR:

If there isn't a way to get back to that menu, I would like to suggest making it possible through an item similar to "constraints" in sketch mode.  I do see there is already a constraints folder, and that's where I'd expect to find a place to modify this.
![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/131182110/a3dbc050-9f2f-405e-86ad-d425272fe6a1)

**Comment by Zolko-123** [comment]
> How do I re-access the "place linked part" dialogue ?

did you try to select the object you wanted to change and click on the 
![image](https://raw.githubusercontent.com/Zolko-123/FreeCAD_Assembly4/8794848cfe440ddc9567c14ef9790ecdb2bdd703/Resources/icons/Place_Link.svg) icon ? 

Or did you try to read the [Instructions](https://github.com/Zolko-123/FreeCAD_Assembly4/blob/master/INSTRUCTIONS.md) ?

**Comment by LibrarySeph** [comment]
I did peruse the instructions.  I did not try clicking that icon.

Upon selecting an Assembly child, this is the tasks view:
![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/131182110/9d89c047-e62d-41a2-9517-7c91863ca683)

After clicking the place link icon, this is the task view:
![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/131182110/48db65e2-6a9a-4c7b-886a-ebe0bcdbfccb)

Is there any reason why the empty task view couldn't show this information by default?  It's empty at the moment.

**Comment by Zolko-123** [comment]
So it all works as expected. What should the task view show if there are no tasks going on ?

**Comment by LibrarySeph** [comment]
If one selects the part, it could show the place linked part dialogue.  Or perhaps a list of potential common options, like using the place link button.  It would help with discoverability quite a bit.

Also, I think it's okay for there to be a difference between "works as expected" in regards to someone who's learning and someone who knows the tool through-and-through.  I'm only one person, as are you.  It takes a lot of people expressing their expectations before trends can be found.  I do not expect my input alone to suit that, but sharing it might help register a valuable shift in user flows sooner.
