### ISSUE TITLE
Q/FR: Why not place LCS after selecting two (or more) aspects?

### ISSUE THREAD

**Issue by LibrarySeph** [Zolko-123/FreeCAD_Assembly4#457]
> Today is my first day messing around with Assembly 4. Please consider this onboarding user testing, I'm clearly not an expert. Maybe someday I will be, but I'll only ever be a novice once.

I love the solution that Assembly 4 uses for TopoNaming, but I'm somewhat confused as to the user-flow for A4.  In most of the tutorials I've seen, people are :
1. choosing a aspect (line, vertex, face, circle), 
    - than adding an LCS, 
    - naming it, 
1. choosing another surface and repeating the above
2. importing and selecting which two (or more) LCS should touch

Is there a specific reason to have this be the workflow, or is it what happened naturally when designing the system?  It is really well built and resilient... I'm going to guess a backend engineer made this.  At the same time, the UX seems like it has a lot of potential to be streamlined.  This is how I would have assumed this plugin worked:
1. import two objects
2. click two+ aspects
3. click add LCS
4. dialogue comes up for naming them all at the same time (separate fields)
5. LCS are added to the external files
6. Task view shows an "Attachment" pane for each new LCS (see photo)
7. Task view also has the "Place Linked Part" dialogue?  (Maybe easier if this is considered a constraint https://github.com/Zolko-123/FreeCAD_Assembly4/issues/456)

![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/131182110/4f0fecb1-c088-456a-94b9-fe50c2d7b726)

I can't think of any dialogues that wouldn't be available with this user flow, but -- to be clear -- I really don't know the depth of this project.  I mostly just want to share the places of confusion I'm running into while learning, and the things I tested first while trying to figure it out.

**Comment by LibrarySeph** [comment]
A person who tends to lean more towards algorithms and less towards pixel pushing.  Sometimes people are amazing at both, but it's often the case that the people who have the most in-depth knowledge of how a thing works are also the ones who have the hardest time seeing what might be confusing about it.

**Comment by Zolko-123** [comment]
Don't understand

**Comment by LibrarySeph** [comment]
The reason I leaned towards A4 was due to people online mentioning that issues didn't stay open long and that the creator was rather humble.  Those are generally good signs for OSS.  Humility usually means being open to working with others, issues are usually closed after resolution.

As a dev with 20 years of experience and who's done multiple design, UX, frontend, and backend positions... the backend side rocks, the UX is lacking.  The amount of clicks to get something done could be cut in half and made much more discoverable.  Above is one suggestion on how to do so.

I really do appreciate your design in terms of the core problem space.  I hope this project reaches its full potential.

**Comment by Zolko-123** [comment]
> As a dev with 20 years of experience ... Above is one suggestion on how to do so

if it is true then you should know that talk is cheap, code is king

BTW : and if you're interested, I'm a mechanical engineer

**Comment by LibrarySeph** [comment]
Talk is not particularly cheap to me, but I run projects a bit differently.  You can't see an entire house from the front yard, many perspectives are required.

And mechanical engineer definitely checks out.  The logic behind your solution is solid.  You can't say I didn't call the backend engineer thing though! :p
