### ISSUE TITLE
Mirrored object > techdraw plot >>> bad mirror on page

### ISSUE THREAD

**Issue by bjnobre** [Zolko-123/FreeCAD_Assembly4#466]
When "show element" property of a mirror object is not set to true, the object is mirrored object is shown on black and the plot on a techdraw page is correct:
![296371773-25cce236-749b-40de-a515-df1316ae39a0](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/20462223/5f78f136-7163-45dd-8265-8cc2f71baf1d)

But when I set the property to true, so I can see mirrored object on color, it shows rotated (perhaps) on techdraw page:
![296371810-cdc19d4f-53df-4be5-9d25-4e473bd351c0](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/20462223/2f9abe83-975b-4ab1-bdfe-167d7f6bede9)

But when I set the property to true, so I can see mirrored object on color, it shows rotated (perhaps) on techdraw page:
![296372060-c9a0fb0d-c8e4-467d-8f93-b9a5d39656c3](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/20462223/44a44988-4ac7-4e69-a838-30fca9e63840)
![296372089-d7148f1a-e98d-42f4-97c9-6970b59f6c7f](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/20462223/f25d2507-e389-4344-9cb7-a97c6889999a)

**Comment by zisoft** [comment]
To see the mirrored object in its original color, open the mirror group and select the original part.
Then switch to the "View" tab, right-click --> Show All

In the "Object Style" group find "Lighting" and set it back to "One side"

**Comment by bjnobre** [comment]
Hi!

There is no such group or property.
![image](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/20462223/55899d2f-60da-4f07-bcf1-8b73ec9164e6)

**Comment by zisoft** [comment]
You have selected an array, try to select the object below.

![Bildschirmfoto 2024-04-03 um 21 41 56](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/4083281/1563fbba-4a2e-4a7e-b5b4-eb72cc5057cf)

**Comment by Zolko-123** [comment]
What is the situation on this subject ?

**Comment by bjnobre** [comment]
It is solved.
