### ISSUE TITLE
Insert Part Dialog in Assembly4 0.50.7,  FreeCAD 0.21.1, on Win10 Obscures Error Message and Locks UI

### ISSUE THREAD

**Issue by alecjames** [Zolko-123/FreeCAD_Assembly4#467]
Environment:
FreeCAD Version: 0.21.1
Assembly4 Version: 0.50.7
Operating System: Windows 10
Description:
When attempting to insert a part into a new, unsaved document using Assembly4, an error message is generated to inform the user that the document needs to be saved first. However, this error message is obscured by the 'Insert Part' dialog, which seems to have a top-most property, making the error message inaccessible. The 'OK' button of the error message box is hidden behind the 'Insert Part' dialog, and the cancel button on the 'Insert Part' dialog becomes inoperative as the dialog loses focus. This results in the application appearing unresponsive.

Steps to Reproduce:

Launch FreeCAD 0.21.1 with Assembly4 0.50.7 on Windows 10.
Try to insert a part into a new, unsaved document.
Expected Result:
An accessible error message prompts the user to save the document before inserting parts.

Actual Result:
The 'Insert Part' dialog obscures the error message, causing the application's UI to lock up. (The 'Insert Part' dialog's cancel button does not function since its not in focus).

Workaround:
Pressing the escape key closes the obscured error message,

**Comment by Zolko-123** [comment]
> this error message is obscured by the 'Insert Part' dialog, which seems to have a top-most property, making the error message inaccessible. The 'OK' button of the error message box is hidden behind the 'Insert Part' dialog, and the cancel button on the 'Insert Part' dialog becomes inoperative as the dialog loses focus

strange, on my system the error message is on top:

![insertpart](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/46596542/1dda431e-57ea-48c9-81e0-5b0f34acb6c0)

**Comment by alecjames** [comment]
I'm on Windows Version 10.0.19045.4046 but in any case the insert part dialog has "topmost" -

![InsertAPartIsTopMost](https://github.com/Zolko-123/FreeCAD_Assembly4/assets/26629256/7d32cb49-274c-4c66-acf1-658f29993f5a)

**Comment by Zolko-123** [comment]
What is the situation with this ?
