### ISSUE TITLE
cannot start assembly 4

### ISSUE THREAD

**Issue by tutut500** [Zolko-123/FreeCAD_Assembly4#47]
![Screenshot_20200222_150020](https://user-images.githubusercontent.com/43301193/75093857-f35a1580-5585-11ea-8d85-d4b937c00e51.png)

OS: Linux 5.3.0-40-generic
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 0.18.4)
Hash: 980bf9060e28555fecd9e3462f68ca74007b70f8
Python version: 2.7.15
Qt version: 5.12.5
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

**Comment by Zolko-123** [comment]
> Important Note: Assembly 4 is not compatible with FreeCAD v0.18 and before, needs FreeCAD >= v0.19.18353
