### ISSUE TITLE
Typo in file

### ISSUE THREAD

**Issue by davids91** [Zolko-123/FreeCAD_Assembly4#472]
I just downloaded this workbench to Freecad 1.21.2 and it crashed with the following message: 

```
invalid syntax. Perhaps you forgot a comma? (FastenersDummy.py, line 55)
```

https://github.com/Zolko-123/FreeCAD_Assembly4/blob/81f55117775bdda07e375d26c8b589f3a266efc4/FastenersDummy.py#L55

So I presume it is a typo because I changed the contents to 

```
"ToolTip": Qtranslate("Fasteners", "FastenersWorkbench is not installed.\n \nYou can install it with the FreeCAD AddonsManager:\nMenu Tools > Addon Manager > fasteners"), 
```

locally and it worked! 

Hope this helps!

**Comment by Zolko-123** [comment]
darn, no, it's the Qtranslate => translate.

**Comment by Zolko-123** [comment]
Hi, I made a new release and I think that the problem is fixed. Could you please update and re-test please ?

**Comment by davids91** [comment]
Yes, indeed! Thanks!

**Comment by davids91** [comment]
Bojler eladó!
