### ISSUE TITLE
invalid literal for int() with base 10

### ISSUE THREAD

**Issue by heeplr** [Zolko-123/FreeCAD_Assembly4#514]
When changing to the Assembly4 WB, there's an error:

```
01:02:04  invalid literal for int() with base 10: 'Unkno'
01:02:04  Traceback (most recent call last):
  File "/home/user/.local/share/FreeCAD/Mod/Assembly4/./InitGui.py", line 90, in Initialize
    git = int(FCver[3][0:5])
```

FreeCAD version: 0.22.0dev from live build on gentoo (which is basically a dev build from current master).

"About" dialog shows:

Version: 0.22.2dev
Revision number: Unknown
Release date: Unknown

**Comment by Zolko-123** [comment]
Do you know how to edit Python files ? Can you try to change the line 90 in `/home/user/.local/share/FreeCAD/Mod/Assembly4/InitGui.py` from 

```
git = int(FCver[3][0:5])
```
to

```
try:
    git = int(FCver[3][0:5])
except:
    git = 666
```

**Comment by heeplr** [comment]
yes, that seems to fix it:

```python
    try:
        git = int(FCver[3][0:5])
    except ValueError:
        git = "unknown"
```
