### ISSUE TITLE
Add LGTM badges

### ISSUE THREAD

**Issue by luzpaz** [Zolko-123/FreeCAD_Assembly4#52]
ref: https://github.com/FreeCAD/FreeCAD-addons/issues/163

**Comment by Zolko-123** [comment]
thank-you for your contribution, but this was 1 step in the wrong direction: while it's nice to have some automatic code analysers, I refuse to acknowledge a "grade" from an automated system. We're not letting SkyNet control us.

**Comment by luzpaz** [comment]
you don't have to use the grade badge then...just use the alert badge ?

**Comment by Zolko-123** [comment]
On mercredi 18 mars 2020 02:56:40 CET luzpaz wrote:
> you don't have to use the grade badge then...just use the alert badge ?

hum, I dunno ... what is the benefit of this ? We want to make good FreeCAD code, not good Python code. 

cheers,

zoltan




-- 

═══════════════
   HUBERT Zoltán 
═══════════════

**Comment by luzpaz** [comment]
@Zolko-123 feel free to discuss it on the [forum thread](https://www.forum.freecadweb.org/viewtopic.php?f=10&t=40228)
