### ISSUE TITLE
[FR] Generate a list of parts in the assembly

### ISSUE THREAD

**Issue by JeffreyFalgout** [Zolko-123/FreeCAD_Assembly4#71]
It would be pretty useful to generate a list of parts that were used to create an assembly, especially if there are duplicates. It would make planning materials purchases that much easier

**Comment by Zolko-123** [comment]
This is called a BoM (Bill of Materials) and yes, this is a missing feature that will be implemented in some (near) future.

**Comment by DerAndere1** [comment]
this feature was added to with [realthunder's FreeCAD 0.19 release 0.11 2020.07.06](https://github.com/realthunder/FreeCAD_assembly3/releases/tag/0.11), You can test if it works with Assembly4 after instaling/updating the Assembly4 workbench using Tools -> Addon manager -> Assembly4.
