### ISSUE TITLE
Edit placement idalog is too wide

### ISSUE THREAD

**Issue by donovaly** [Zolko-123/FreeCAD_Assembly4#80]
After inserting a part, I use the menu  Assembly->Edit Placement of Part. The appearing Task dialog is much too wide:

![FreeCAD_3NfEIGBxpc](https://user-images.githubusercontent.com/1828501/85857622-80bea800-b7ba-11ea-9276-e5cfa2c3b268.png)

This suddenly happened in my assembly after I already called this dialog for other parts and that time the dialog had the correct size.
I restarted FreeCAD but the problem remained.

I found the problem:
There is one part in the assembly with a large name:
![FreeCAD_TT82hdrk11](https://user-images.githubusercontent.com/1828501/85857988-1eb27280-b7bb-11ea-8f5b-3f15c0b4ddc2.png)

So it is correct that the Task dialog is that wide. But for the other parts, the name is much shorter thus the dialog should fit to the length if the name.
This is currently not the case because I can for example made the dialog so small that one cannot read the full name:
![FreeCAD_xnRa98YyGM](https://user-images.githubusercontent.com/1828501/85858047-35f16000-b7bb-11ea-9015-437db7e5ea3b.png)

I use Assembly 0.9.6 and
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21769 (Git)
Build type: Release
Branch: master
Hash: 801bfe4ba5f0910e9b2885917c521ab7fd8e9020
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)

**Comment by Zolko-123** [comment]
ah, OK, yes: I think it's because of a default Qt behaviour that stretches a widget to the text length. I'll set a maximum length (but then you'll have to scroll to see the name)

**Comment by donovaly** [comment]
> I'll set a maximum length

This would not be right. Instead the dialog should be as wide as necessary to contain the content. I only know the C++ connection to Qt and there you set this via the UI file.

I opt for this because it is quicker to move the splitter to the side to see the dialog in full size than to scroll in its different textEdits.

**Comment by donovaly** [comment]
> Any news on this ? Is this still a problem ?

Still a problem with 0.9.8 and latest FC master.

By the way, the release 0.9.8 does not appear here: https://github.com/Zolko-123/FreeCAD_Assembly4/releases

**Comment by Zolko-123** [comment]
yeah, I didn't touch this lately.

**Comment by kravietz81** [comment]
Can you strict widness of that dialog to some value and if name is too long show it as pop-up comment??

Did you consider wrapping of too long names??

**Comment by Zolko-123** [comment]
fixed, please update and check

**Comment by donovaly** [comment]
Many thanks. The bug is now fixed.
