### ISSUE TITLE
Wrong warning in report panel on placing parts

### ISSUE THREAD

**Issue by donovaly** [Zolko-123/FreeCAD_Assembly4#81]
I added a new part to the main model. In the placement dialog I am in this state:

![FreeCAD_076MBV6Qom](https://user-images.githubusercontent.com/1828501/85872883-aa82c980-b7d0-11ea-9b54-967e85badba1.png)

Now I need to select the LCS and I need to start with one of the 2. But no matter if I select at first the linked LCS or the parent LCS, I always get immediately this warning: "Problem in selections" in the report panel.

This warning should only be issued if the selections are incompatible etc. As it is you get it in the normal use case.

**Comment by Zolko-123** [comment]
Yes, I have seen that. will try to correct

**Comment by Zolko-123** [comment]
I believe it's corrected now

**Comment by donovaly** [comment]
I tested today and I still get the incorrect warning.
