### ISSUE TITLE
[enhancement] Allow to spefify how to rotate in placement dialog

### ISSUE THREAD

**Issue by donovaly** [Zolko-123/FreeCAD_Assembly4#85]
When placing a part, one gets a dialog with 3 buttons "Rot X" etc. These rotate always 90°. But there are (not so rare) cases where one needs a different angle. Take e.g. this example:
![FreeCAD_bOnIHH42kI](https://user-images.githubusercontent.com/1828501/86042696-d52a8780-ba47-11ea-8774-0c9b754479ae.png)

Here I need at first a rotation by 90° around the y-axis, then subsequently a rotation of 30° around the z-axis.

I know this is a bit tricky because as it currently, one can only rotate around one axis. 

I thought about it, and I think now the solution would be to add to the placement dialog the attachment part of FC's datum/primitives dialog. This would allow to rotate around several axes and also fix issue #78. But let me think about this more.

**Comment by Zolko-123** [comment]
I agree with #78 but not on this one.
