### ISSUE TITLE
LCS not moving on part when Scale Vector applied

### ISSUE THREAD

**Issue by joshmorelli** [Zolko-123/FreeCAD_Assembly4#88]
I created an assembly to model a PVC structure with multiple parts for fittings, and a single part for the pipe, The pipe part is one inch long with the intention that a scale vector is applied in a single dimension to model multiple lengths of pipe from a single part. An LCS was created at both ends of the pipe and when the scale vector was applied, the LCS at one end of the pipe appeared to move in the GUI. However, when attempting to attach a part to that LCS, only the original location of the LCS (at the one-inch point) was used. My suspicion is that when placing a part, only the original part's LCS is referenced, not the scaled model in the assembly. Please confirm whether this is the case, or if I am doing something wrong when scaling or linking the part.

In the image below, the elbow should be attached at the right end of the 6-inch pipe, but instead, it's attached at the 1-inch point from the original part.
![2020-07-04_2332](https://user-images.githubusercontent.com/52676940/86524977-f841a680-be4e-11ea-9577-522523da5d47.png)

Assembly4 version 0.9.7

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21775 (Git)
Build type: Release
Branch: master
Hash: 1f741aa511e898849e46ed14515fce416fe32acb
Python version: 3.8.2
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by Zolko-123** [comment]
Yes, you are right, scaling doesn't work well. I suggest not to use it apart for demonstrative purposes.
