### ISSUE TITLE
Difficulty to deal with links to external files in A4

### ISSUE THREAD

**Issue by wayofwood** [Zolko-123/FreeCAD_Assembly4#89]
FreeCAD woodworking challenge

I was trying my hands on developing a few features to make my life as a woodworker easier. 

FreeCAD version, A4 from July 14th, 2020

> OS: Ubuntu 20.04 LTS
> Word size of OS: 64-bit
> Word size of FreeCAD: 64-bit
> Version: 0.19.21718 (Git) AppImage
> Build type: Release
> Branch: master
> Hash: 002e25b5617f2c79f65968f1f82f7267899965c3
> Python version: 3.8.2
> Qt version: 5.12.5
> Coin version: 4.0.0
> OCC version: 7.4.0
> Locale: German/Germany (de_DE)

**In order to reproduce the issue:**

1. Create a document main with a spreadsheet named p and an A4 model
2. Put a number in a cell and add an alias "test"
3. Create a second document sub, create an A4 part, and a part design that uses `<<main>>#<<p>>.test` as a dimension
4. Insert the sub part in the main assembly

This throws an error: `<Gui> Document.cpp(1052): Document::getDependentDocuments: The graph must be a DAG.`

When closing and re-opening the main document the part is not visible and a similar error is launched. 

Here is a sample file: [test.zip](https://github.com/Zolko-123/FreeCAD_Assembly4/files/4920093/test.zip)

When opening the sub file and replacing the reference by `main#<<p>>.test` (I don't know which one is the correct way according to the new nomenclature)and then linking it to the main assembly results in a different error message: Recompute failed! Please check report view.
`<Exception> Invalid type 'NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
in property binding 'Constraints'
5.38848 <App> Document.cpp(3738): Failed to recompute suba4#Sketch: Invalid type 'NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE'
in property binding 'Constraints'`

**Why is this relevant?**

I like to store all relevant dimensions of a model in a central spreadsheet. When having a lot of parameters this results in a cleaner model and it would be great if A4 would support this type of reference.

**Comment by Zolko-123** [comment]
FreeCAD thinks that there is a circular dependency, it's independent from Asm4. You have to organise your work differently.
