### ISSUE TITLE
"Add Variable" has error when using a Name with space inside

### ISSUE THREAD

**Issue by wang02139** [Zolko-123/FreeCAD_Assembly4#96]
Thanks for making the tool. It's great. If we can fix a few usability issues, it'd be very popular.

In the "Add Variable" dialog, if I press "Enter", the variable is added but the dialog remain open. The dialog should close after the variable is added. Similarly, the dialog should close after "OK" is clicked.

![Screenshot from 2020-08-21 09-38-35](https://user-images.githubusercontent.com/8675499/90914345-9d2e2980-e392-11ea-8ea0-5238b9180924.png)

**Comment by wang02139** [comment]
I figured out the condition for the bug. If the variable name has a space in it, such as "foo bar", the dialog will not close. There is a python error, but the variable with space replaced by "_" is added.

If I use a variable name without space, everything works fine.

**Comment by Zolko-123** [comment]
Can I close this then ?

**Comment by cheuksan** [comment]
Can you fix the error handling of adding a variable with a space inside?

**Comment by wang02139** [comment]
Can you fix the handling of adding a variable with space inside?

**Comment by Zolko-123** [comment]
No, you cannot use variables with spaces. There is no software language that allows this.

**Comment by wang02139** [comment]
I know. e.g. If I add the variable "a b", the tool adds the variable "a_b", but the dialog remains open. The dialog box should close after "a_b" is added.

**Comment by wang02139** [comment]
This is the backtrace:

22:54:13  Traceback (most recent call last):
22:54:13    File "/home/wang/.FreeCAD/Mod/Assembly4/VariablesLib.py", line 128, in onOK
22:54:13      setattr( self.Variables, varName, varValue )
22:54:13  AttributeError: 'FeaturePython' object has no attribute 'x y'

**Comment by wang02139** [comment]
I just made a pull request for it. Please review. thanks!
